version: '{build}'

skip_commits:
  files:
    - '**/*.md'

image: Visual Studio 2019

init:
  - cmd: git config --global core.autocrlf false
  - ps: |
      $ErrorActionPreference = "Stop"
      $tagName = $env:APPVEYOR_REPO_TAG_NAME
      if ($tagName -match '^v\d+\.\d+') # tag name starts with 'vX.Y'
      {
        $env:SHOULD_PUBLISH_NUGET_PACKAGE = "true"
        Write-Host "Will publish nuget package for $tagName tag" -ForegroundColor "Green"
        if ($tagName -match '^v\d+\.\d+-release') # tag name starts with 'vX.Y-release' (e.g. use 'v4.2-release.1' tag for the first patch for release v4.2)
        {
          $env:SHOULD_CREATE_RELEASE = "true"
          Write-Host "Will create release for $tagName tag" -ForegroundColor "Green"
        }
      }

nuget:
  disable_publish_on_pr: true

before_build:
  - cmd: dotnet --info
  - cmd: dotnet restore --verbosity minimal

build_script:
  - cmd: dotnet build --no-restore --configuration Release
  - cmd: dotnet pack --no-build --configuration Release

before_test:
  - cmd: docker-compose up
  - ps: |
      docker container ls --format "{{.Names}}" | ForEach-Object {
        do {
            Start-Sleep 5
            $status = docker inspect -f "{{.State.Health.Status}}" $_
            Write-Host "Container $_ status: $status"
        }
        while($status -ne "healthy")
      }

test_script:
  - cmd: dotnet test --no-build --verbosity normal --configuration Release --logger trx

after_test:
  - cmd: docker-compose down
  - ps: |
      $wc = New-Object 'System.Net.WebClient'
      Get-ChildItem -Path .\SqlStorageCoreTests\TestResults\ - Filter *.trx -File | ForEach-Object {
        $wc.UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", $_.FullName)
      }

artifacts:
  - path: './SqlStorageCore/bin/Release/*.nupkg'

deploy:
  - provider: NuGet
    server: https://nuget.org
    api_key:
      secure: CQ4MGAZ56ySfApnQ2TeZhSYDs+yLTggiu+5EWVsJBF9xn/pKcOO9IelQM6qA0mbf
    skip_symbols: true
    on:
      SHOULD_PUBLISH_NUGET_PACKAGE: true

  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
      secure: y8dDOcAtq4U1MTDJFX8f23xsvyFU1u4bhwr9Lzbkf2revNWPPTifBkWghris9v8i
    draft: false
    prerelease: false
    on:
      SHOULD_CREATE_RELEASE: true
